defmodule KickTrackerWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :kick_tracker

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_kick_tracker_key",
    signing_salt: "AW+Zg9jz",
    same_site: "Lax"
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :kick_tracker,
    gzip: not code_reloading?,
    only: KickTrackerWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :kick_tracker
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  # The visitor's address behind Caddy (and Cloudflare), for rate limits.
  plug KickTrackerWeb.Plugs.RemoteIp
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint], log: {__MODULE__, :log_level, []}

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug KickTrackerWeb.Router

  @doc """
  The level of a request's "GET /path" log line. Phoenix logs the path
  as is, and an invitation link from before links moved the token into
  the query (`/admin/invite/<token>`) carries it in the path: those are
  not logged. Query strings aren't logged, and params go through
  `:filter_parameters`.
  """
  def log_level(%Plug.Conn{path_info: ["admin", "invite", _ | _]}), do: false
  def log_level(_conn), do: :info
end
